# Generated by Django 5.0.1 on 2024-01-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('planting_season', models.CharField(max_length=50)),
                ('harvest_season', models.CharField(max_length=50)),
                ('maturity_period', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='crops/images')),
            ],
        ),
    ]
